#pragma once
#include <iostream>
#include <string>
#include <vector>
#include "SFML/System.hpp"
#include "SFML/Graphics.hpp"
#include "Engine.h"
#include "SceneManager.h"
#include "Input.h"
#include "Collider.h"
#include "Settings.h"